name: Generate NOTICE

on:
    push:
        paths:
            - "package.json"

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: "15"

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install
              run: yarn install

            - name: Generate NOTICE
              run: yarn licenses generate-disclaimer >> NOTICE

            - name: Commit and Push
              uses: EndBug/add-and-commit@v7
              with:
                  add: "NOTICE"
                  author_name: github-actions[bot]
                  author_email: 41898282+github-actions[bot]@users.noreply.github.com
                  message: "Generate NOTICE"
                  push: true
